# Generated by Django 5.1.1 on 2024-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_application', models.CharField(default='Django Apps', max_length=200, unique=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('rate', models.FloatField(default=0)),
                ('url_link', models.TextField(unique=True)),
                ('all_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
