# Generated by Django 5.1.1 on 2024-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='type_of_application',
            field=models.CharField(default='Django Apps', max_length=200),
        ),
    ]
