# Generated by Django 5.1.1 on 2024-10-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_applicationmodel_type_of_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='rate',
        ),
    ]
