# Generated by Django 5.1.1 on 2024-10-06 18:37

import web_page.main_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_aboutmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[web_page.main_page.models.min_length_validator])),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60, unique=True, validators=[web_page.main_page.models.min_length_validator])),
            ],
        ),
        migrations.DeleteModel(
            name='AboutModel',
        ),
    ]
