# Generated by Django 5.1.1 on 2024-10-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_aboutmemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='type_of_application',
            field=models.CharField(choices=[('Django Apps', 'Django Apps'), ('Data Structures', 'Data Structures'), ('Other', 'Other'), ('Flask Apps', 'Flask Apps')], default='Django Apps', max_length=20),
        ),
    ]
