# Generated by Django 5.1.1 on 2024-10-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_applicationmodel_type_of_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
